package io.kanon.specctl.core.plugin;

import io.kanon.specctl.core.json.JsonSupport;
import io.kanon.specctl.ir.CanonicalIr;
import io.kanon.specctl.ir.StableIds;

import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

final class PluginSupport {
    private PluginSupport() {
    }

    static PluginRuntime.RegisteredPlugin registered(PluginManifest manifest, CompilerPlugin plugin) {
        return new PluginRuntime.RegisteredPlugin(manifest, plugin);
    }

    static PluginManifest bootstrapManifest() {
        return new PluginManifest("bootstrap", "0.2.0", List.of(), ExecutionPhase.MODEL, List.of(
                "src/generated/java/bootstrap",
                "src/generated/resources/config",
                "src/generated/build"
        ));
    }

    static PluginManifest domainManifest() {
        return new PluginManifest("domain", "0.2.0", List.of("bootstrap"), ExecutionPhase.MODEL, List.of("src/generated/java/domain"));
    }

    static PluginManifest runtimeManifest() {
        return new PluginManifest("runtime", "0.2.0", List.of("domain"), ExecutionPhase.RUNTIME, List.of("src/generated/java/runtime"));
    }

    static PluginManifest apiManifest() {
        return new PluginManifest("api", "0.2.0", List.of("domain", "runtime"), ExecutionPhase.RUNTIME, List.of("src/generated/java/api"));
    }

    static PluginManifest persistenceManifest() {
        return new PluginManifest("persistence", "0.2.0", List.of("domain"), ExecutionPhase.RUNTIME, List.of(
                "src/generated/java/persistence",
                "src/generated/resources/db/migration"
        ));
    }

    static PluginManifest messagingManifest() {
        return new PluginManifest("messaging", "0.2.0", List.of("domain"), ExecutionPhase.RUNTIME, List.of("src/generated/java/messaging"));
    }

    static PluginManifest securityManifest() {
        return new PluginManifest("security", "0.2.0", List.of("domain"), ExecutionPhase.RUNTIME, List.of("src/generated/java/security"));
    }

    static PluginManifest observabilityManifest() {
        return new PluginManifest("observability", "0.2.0", List.of("domain"), ExecutionPhase.RUNTIME, List.of("src/generated/java/obs"));
    }

    static PluginManifest contractManifest() {
        return new PluginManifest("contracts", "0.2.0", List.of("api"), ExecutionPhase.CONTRACT, List.of("src/generated/resources/contracts"));
    }

    static String provenanceHeader(GenerationContext context) {
        String irHash = StableIds.sha256(JsonSupport.stableJson(context.ir()));
        return "// generated by " + context.manifest().name()
                + " version " + context.manifest().version()
                + " irHash=" + irHash
                + " specVersion=" + context.ir().specVersion()
                + System.lineSeparator();
    }

    static String mapType(String specType) {
        return switch (specType) {
            case "UUID" -> "java.util.UUID";
            case "LocalDate" -> "java.time.LocalDate";
            case "Instant" -> "java.time.Instant";
            case "int" -> "int";
            case "long" -> "long";
            default -> "String";
        };
    }

    static String mapJsonType(String specType) {
        return switch (specType) {
            case "int", "long" -> "integer";
            default -> "string";
        };
    }

    static String sqlType(String specType) {
        return switch (specType) {
            case "UUID" -> "uuid";
            case "LocalDate" -> "date";
            case "Instant" -> "timestamp";
            case "int" -> "integer";
            case "long" -> "bigint";
            default -> "varchar(255)";
        };
    }

    static String lowerFirst(String input) {
        return Character.toLowerCase(input.charAt(0)) + input.substring(1);
    }

    static Optional<String> securityExpression(CanonicalIr ir, String commandName) {
        if (ir.security() == null) {
            return Optional.empty();
        }
        return ir.security().policies().stream()
                .filter(policy -> policy.command().equals(commandName))
                .flatMap(policy -> policy.preAuthorize().stream())
                .findFirst();
    }

    static String eventSchema(CanonicalIr.Event event) {
        Map<String, Object> properties = event.payload().stream()
                .collect(Collectors.toMap(CanonicalIr.Field::name, field -> Map.of("type", mapJsonType(field.type()))));
        return JsonSupport.stableJson(Map.of(
                "$id", event.name() + ".v" + event.schema().version(),
                "type", "object",
                "properties", properties,
                "required", event.payload().stream().map(CanonicalIr.Field::name).toList(),
                "additionalProperties", false
        ));
    }
}
